version: 1.12.4-{build}

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\http

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  # https://www.msys2.org/news/#2020-05-17-32-bit-msys2-no-longer-actively-supported
  - curl -SL http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz -oC:\msys2-keyring.txz
  - curl -SL http://repo.msys2.org/msys/x86_64/msys2-keyring-1~20210904-1-any.pkg.tar.zst -oC:\msys2-keyring.tzst
  - curl -SL http://repo.msys2.org/msys/x86_64/zstd-1.4.7-1-x86_64.pkg.tar.xz -oC:\zstd.txz
  - curl -SL http://repo.msys2.org/msys/x86_64/pacman-5.2.2-5-x86_64.pkg.tar.xz -oC:\pacman.txz
  - pacman --noconfirm -U C:\msys2-keyring.txz
  - pacman --noconfirm -U C:\zstd.txz
  - pacman --noconfirm -U C:\pacman.txz
  - pacman --noconfirm -U C:\msys2-keyring.tzst
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy pacman"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -Su"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-nsis unzip"
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="x86_64-pc-windows-gnu"
  -
  - curl -SOL https://gistcdn.githack.com/nabijaczleweli/880a4b42368c610dc5de041d73bbea58/raw/7f3a23efe680d06934e6c0d7c9fbe92216da0682/EnVar_plugin.zip
  - unzip -j EnVar_plugin.zip Plugins/amd64-unicode/EnVar.dll -d C:\msys64\mingw64\share\nsis\Plugins\unicode

build: off
build_script:
  - git submodule update --init --recursive
  - cargo build --verbose --release
  - cp target\release\http.exe http-v1.12.4.exe
  - strip --strip-all --remove-section=.comment --remove-section=.note http-v1.12.4.exe
  - makensis -DHTTP_VERSION=v1.12.4 install.nsi

test: off
test_script:
  - cargo test --verbose --release

artifacts:
  - path: http-v1.12.4.exe
  - path: http v1.12.4 installer.exe

deploy:
  provider: GitHub
  artifact: /http.*v1.12.4.*\.exe/
  auth_token:
    secure: ZTXvCrv9y01s7Hd60w8W7NaouPnPoaw9YJt9WhWQ2Pep8HLvCikt9Exjkz8SGP9P
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
    on_build_success: false
