[package]
# "http" was taken, "https" (with 's' apparently standing for "server") is free
name = "https"
description = "Host These Things Please - a basic http server for hosting a folder fast and simply"
repository = "https://github.com/thecoshman/http"
readme = "README.md"
keywords = ["http", "server", "https", "file", "directory"]
categories = ["network-programming", "web-programming::http-server"]
license = "MIT"
build = "build.rs"
# Remember to also update in appveyor.yml
version = "1.5.0"
# Remember to also update in http.md
authors = ["thecoshman <rust@thecoshman.com>",
           "nabijaczleweli <nabijaczleweli@gmail.com>",
           "pheki"]

[dependencies]
hyper-native-tls = "0.2"
lazy_static = "1.2"
serde_json = "0.9"
mime_guess = "1.8"
lazysort = "0.2"
brotli2 = "0.3"
unicase = "2.2"
base64 = "0.10"
flate2 = "1.0"
rfsapi = "0.1"
bzip2 = "0.3"
ctrlc = "3.1"
regex = "1.1"
serde = "0.9"
clap = "2.32"
rand = "0.6"
time = "0.1"
url = "1.7"
md6 = "2.0"

[dependencies.trivial_colours]
version = "0.3"
default-features = false

[dependencies.iron]
version = "0.6"
features = ["hyper-native-tls"]

[target.'cfg(not(any(target_os = "windows", target_os = "macos")))'.dependencies.libc]
version = "0.2"

[build-dependencies]
embed-resource = "1.1"

[target.'cfg(not(any(target_os = "windows", target_os = "macos")))'.build-dependencies.cc]
version = "1.0"


[[bin]]
name = "http"
path = "src/main.rs"
test = false
doc = false

[[bin]]
name = "httplz"
path = "src/main.rs"
test = false
doc = false
