[package]
# "http" was taken, "https" (with 's' apparently standing for "server") is free
name = "https"
description = "Host These Things Please - a basic http server for hosting a folder fast and simply"
repository = "https://github.com/thecoshman/http"
readme = "README.md"
keywords = ["http", "server", "https", "file", "directory"]
categories = ["network-programming", "web-programming::http-server"]
license = "MIT"
build = "build.rs"
# Remember to also update in appveyor.yml
version = "1.2.0"
# Remember to also update in http.md
authors = ["thecoshman <thecoshman@gmail.com>",
           "nabijaczleweli <nabijaczleweli@gmail.com>"]

[dependencies]
hyper-native-tls = "0.2"
lazy_static = "0.2"
mime_guess = "1.8"
lazysort = "0.1"
brotli2 = "0.2"
unicase = "1.4"
base64 = "0.5"
flate2 = "0.2"
bzip2 = "0.3"
ctrlc = "3.0"
clap = "2.23"
time = "0.1"
url = "1.4"
md6 = "1.1"

[dependencies.trivial_colours]
version = "0.3"
default-features = false

[dependencies.iron]
version = "0.5"
features = ["hyper-native-tls"]

[build-dependencies]
embed-resource = "1.1"


[[bin]]
name = "http"
test = false
doc = false
